// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace chameleon
{
		public class ChamConstant
		{
			public static int ANTI_ADDICTION_UNKNOWN = 0;
			public static int ANTI_ADDICTION_CHILD = 1;
			public static int ANTI_ADDICTION_ADULT = 2;

			public enum ErrorCode {
				ERR_INTERNAL = -1, // some internal error happened...
				ERR_OK = 0, // OK
				ERR_CANCEL = 1,
				ERR_UNKNOWN = 2,
				ERR_ILL_PARAMS = 3,
				ERR_FAIL = 4,
			
			// pay action erros 11~ 20
				ERR_PAY_FAIL = 11, // fail to pay
				ERR_PAY_CANCEL = 12, // user cancel the payment
				ERR_PAY_IN_PROGRESS = 13 // payment is in progress..
			}
		}
}

