#ifndef __ChameleonErrorCode_H_
#define __ChameleonErrorCode_H_

namespace Chameleon {
enum {
    CHAMELEON_ERR_INTERNAL = -1,
    CHAMELEON_ERR_OK = 0,
    CHAMELEON_ERR_CANCEL = 1,
    CHAMELEON_ERR_UNKNOWN = 2,
    CHAMELEON_ERR_ILL_PARAM = 3,
    
    CHAMELEON_ERR_PAY_FAIL = 11,
    CHAMELEON_ERR_PAY_CANCEL = 12,
    CHAMELEON_ERR_PAY_IN_PROGRESS = 13,
};

enum {
    CHAMELEON_ANTIADDICTION_UNKNOWN = 0,
    CHAMELEON_ANTIADDICTION_CHILD = 1,
    CHAMELEON_ANTIADDICTION_ADULE = 2
};

enum  {
    CHAMELEON_SDK_UI_OPEN = 0,
    CHAMELEON_SDK_UI_CLOSE = 1
};

}

#endif //__ChameleonErrorCode_H_
