/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class prj_chameleon_channelapi_cbinding_ChannelAPINative */

#ifndef _Included_prj_chameleon_channelapi_cbinding_ChannelAPINative
#define _Included_prj_chameleon_channelapi_cbinding_ChannelAPINative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    init
 * Signature: (Z[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_init
  (JNIEnv *, jclass, jboolean, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    preAccountSwitch
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_preAccountSwitch
  (JNIEnv *, jclass);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    afterAccountSwitch
 * Signature: (I[B[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_afterAccountSwitch
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onAccountLogout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onAccountLogout
  (JNIEnv *, jclass);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onGuestBind
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onGuestBind
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onLoginGuest
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onLoginGuest
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onLogin
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onLogin
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onRegistGuest
 * Signature: (II[B[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onRegistGuest
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onCharge
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onCharge
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onBuy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onBuy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onSwitchAccount
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onSwitchAccount
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onPause
  (JNIEnv *, jclass);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onAntiAddiction
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onAntiAddiction
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onProtocolDone
 * Signature: (II[B[B)V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onProtocolDone
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray);


/*
 * Class:     prj_chameleon_channelapi_cbinding_ChannelAPINative
 * Method:    onExit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_onExit
  (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_prj_chameleon_channelapi_cbinding_ChannelAPINative_submitPlayerInfo
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
